# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Lints the source code separately, outside of the OS x Node version matrix.
  # This is separate because linting is one of the most time-consuming parts of the build, and the matrix causes it to run multiple times.
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Lint code
      run: npm run lint-full

  # Build the code and run all tests
  build-and-test:
    name: Build and test project
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Run all tests
      run: npm test

  # Upload artifacts
  # This runs one final build (without a matrix) to produce compiled output, then generates docs.
  # Docs and build artifacts are all uploaded
  dist:
    name: Generate code and documentation artifacts
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Generate documentation
      run: npm run docs
    - name: Upload code artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mooltipage-dist
        path: |
          dist/
          package.json
          package-lock.json
          LICENSE
          README.md
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mooltipage-docs
        path: docs/
