# Generates documentation and updates github pages
# Please note - commits including this file cannot be pushed from some IDEs (including all JetBrains products).
# As a workaround, push the commit using the git CLI.

name: Build

on:
  push:
    branches: [ master ]

jobs:
  # Builds, generates, and uploads docs
  docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Generate documentation
        run: npm run docs
      - name: Upload code artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mooltipage-dist
          path: |
            dist/
            package.json
            package-lock.json
            LICENSE
            README.md
          if-no-files-found: error
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mooltipage-docs
          path: docs/
          if-no-files-found: error